# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('WRITING', 'Writing'), ('READING', 'Reading'), ('MATH', 'Math'), ('CORE', 'Core Knowledge')], max_length=256, verbose_name='Subject')),
                ('title', models.CharField(max_length=256, verbose_name='Title of Video')),
                ('shareurl', models.CharField(max_length=500, verbose_name='Greeting')),
            ],
        ),
    ]
