# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='lesson_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='The date the lesson is scheduled for.', verbose_name='Lesson Date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='shareurl',
            field=models.CharField(help_text='The Google Drive Share Link URL', max_length=500, verbose_name='URL'),
        ),
    ]
