# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0039_auto_20161103_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgi_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('question', models.CharField(max_length=500, unique=True)),
                ('first_num_low', models.IntegerField()),
                ('first_num_high', models.IntegerField()),
                ('second_num_low', models.IntegerField()),
                ('second_num_high', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CGI Question',
                'verbose_name_plural': 'CGI Questions',
            },
        ),
        migrations.CreateModel(
            name='CGIResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passfail', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=255)),
                ('cgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathcgi.CGI')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'CGI Result',
                'verbose_name_plural': 'CGI Results',
            },
        ),
    ]
