# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathcgi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgi',
            name='gr2_unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
