# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathcgi', '0004_auto_20161104_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgi',
            name='gr2_unit',
            field=models.IntegerField(blank=True, default=1, help_text='The Unit in the Grade 2 Scope and Sequence which the CGI is introduced', verbose_name='Grade 2 Unit'),
            preserve_default=False,
        ),
    ]
