# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathcgi', '0006_auto_20161104_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgi',
            name='cgi_number',
            field=models.IntegerField(unique=True, verbose_name='CGI #'),
        ),
        migrations.AlterField(
            model_name='cgi',
            name='date_assigned',
            field=models.DateField(blank=True, help_text='Date the CGI was/will be given to the class.', null=True, verbose_name='Date Assigned'),
        ),
        migrations.AlterField(
            model_name='cgi',
            name='name',
            field=models.CharField(help_text='Name of the first person mentioned in the problem.', max_length=50, unique=True, verbose_name='Character Name'),
        ),
        migrations.AlterField(
            model_name='cgi',
            name='question',
            field=models.CharField(help_text='Substitute __ for the numbers in the problem.', max_length=500, unique=True, verbose_name='Problem'),
        ),
    ]
