# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathcgi', '0008_auto_20161106_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgiresult',
            name='passfail',
        ),
        migrations.AddField(
            model_name='cgiresult',
            name='progress',
            field=models.CharField(choices=[('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', 'M')], default='-', help_text='- : Not Yet Tested, 0 : Zero Streak, 1 : One Streak, 2 : Two Streak, M : Mastered', max_length=100, verbose_name='Progress'),
        ),
    ]
