# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathcgi', '0009_auto_20161106_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgiresult',
            name='comment',
        ),
    ]
