# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathcgi', '0010_remove_cgiresult_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cgi',
            options={'ordering': ['cgi_number'], 'verbose_name': 'CGI Question', 'verbose_name_plural': 'CGI Questions'},
        ),
        migrations.AlterModelOptions(
            name='cgiresult',
            options={'ordering': ['cgi'], 'verbose_name': 'CGI Result', 'verbose_name_plural': 'CGI Results'},
        ),
    ]
