# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 18:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IXLSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\w\\-\\w\\.\\d+$', 'Pattern must match IXL format: D-A.12')])),
                ('skill_description', models.CharField(max_length=200)),
                ('ixl_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IXLSkillScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('score', models.IntegerField()),
                ('ixl_skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.IXLSkill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoster',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='ixlskillscores',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster'),
        ),
    ]
