# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brain', '0004_auto_20160725_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('grade', models.CharField(choices=[('K', 'Kindergarten'), ('1ST', '1st Grade'), ('2ND', '2nd Grade'), ('3RD', '3rd Grade'), ('4TH', '4th Grade'), ('5TH', '5th Grade'), ('6TH', '6th Grade'), ('7TH', '7th Grade'), ('8TH', '8th Grade')], default='2ND', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentroster',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 25, 11, 32, 50, 890200, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentroster',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentroster',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50),
        ),
        migrations.AddField(
            model_name='currentclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brain.Teacher'),
        ),
        migrations.AddField(
            model_name='studentroster',
            name='current_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brain.CurrentClass'),
        ),
    ]
