# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_auto_20160725_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='id',
        ),
    ]
