# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_auto_20160725_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentroster',
            old_name='email',
            new_name='Parent Email',
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50),
        ),
    ]
