# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_auto_20160725_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentroster',
            name='Parent Email',
        ),
        migrations.AddField(
            model_name='studentroster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Parent Email'),
        ),
    ]
