# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0010_auto_20160725_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentclass',
            name='grade',
            field=models.CharField(choices=[('K', 'Kindergarten'), ('1st', '1st Grade'), ('2nd', '2nd Grade'), ('3rd', '3rd Grade'), ('4th', '4th Grade'), ('5th', '5th Grade'), ('6th', '6th Grade'), ('7th', '7th Grade'), ('8th', '8th Grade')], default='2nd', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_user',
            field=models.CharField(max_length=50),
        ),
    ]
