# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0011_auto_20160801_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_user',
            new_name='teacher',
        ),
    ]
