# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0013_auto_20160801_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentroster',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
