# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0017_auto_20160802_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ixlskillscores',
            name='ixl_skill_id',
        ),
        migrations.RemoveField(
            model_name='ixlskillscores',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='IXLSkill',
        ),
        migrations.DeleteModel(
            name='IXLSkillScores',
        ),
    ]
