# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0018_auto_20160802_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentroster',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50),
        ),
    ]
