# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0020_auto_20160805_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentclass',
            name='year',
            field=models.CharField(choices=[(14, '14-15'), (15, '15-16'), (16, '16-17'), (17, '17-18'), (18, '18-19'), (19, '19-20'), (20, '20-21'), (21, '21-22')], max_length=100),
        ),
    ]
