# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0022_auto_20160927_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ixluser', models.CharField(blank=True, max_length=200)),
                ('ixlpass', models.CharField(blank=True, max_length=200)),
                ('kidsazteacher', models.CharField(blank=True, max_length=200)),
                ('kidsazuser', models.CharField(blank=True, max_length=200)),
                ('kidsazpass', models.CharField(blank=True, max_length=200)),
                ('myonuser', models.CharField(blank=True, max_length=200)),
                ('myonpass', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'Account Information',
                'verbose_name_plural': 'Account Information',
            },
        ),
    ]
