# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0024_auto_20161002_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='ixlpass',
            field=models.CharField(blank=True, max_length=200, verbose_name='IXL Password'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='ixluser',
            field=models.CharField(blank=True, max_length=200, verbose_name='IXL Username'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='kidsazpass',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kids A-Z Password'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='kidsazuser',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kids A-Z Username'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='myonpass',
            field=models.CharField(blank=True, max_length=200, verbose_name='myON Password'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='myonuser',
            field=models.CharField(blank=True, max_length=200, verbose_name='myON Username'),
        ),
    ]
