# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0025_auto_20161002_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lexile', models.IntegerField(blank=True, verbose_name='Current Lexile Level')),
                ('goal_lexile', models.IntegerField(blank=True, verbose_name='Goal Lexile Level')),
                ('myon_tests_taken', models.IntegerField(blank=True, verbose_name='myON Tests Taken')),
                ('current_dra', models.CharField(blank=True, max_length=10, verbose_name='Current DRA Level')),
                ('goal_dra', models.CharField(blank=True, max_length=10, verbose_name='Goal DRA Level')),
                ('kidsazuser', models.CharField(blank=True, max_length=200, verbose_name='Kids A-Z Username')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'Reading Statistic',
                'verbose_name_plural': 'Reading Statistics',
            },
        ),
    ]
