# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0026_readingstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingstats',
            name='kidsazuser',
        ),
    ]
