# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0027_remove_readingstats_kidsazuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstats',
            name='current_lexile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Lexile Level'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='goal_lexile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goal Lexile Level'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='myon_tests_taken',
            field=models.IntegerField(blank=True, null=True, verbose_name='myON Tests Taken'),
        ),
    ]
