# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0028_auto_20161002_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstats',
            name='myon_time_spent',
            field=models.IntegerField(blank=True, null=True, verbose_name='myON Time Spent'),
        ),
    ]
