# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0030_readingstats_starting_lexile'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstats',
            name='myon_books_finished',
            field=models.IntegerField(blank=True, null=True, verbose_name='myON Books Finished'),
        ),
        migrations.AddField(
            model_name='readingstats',
            name='myon_books_opened',
            field=models.IntegerField(blank=True, null=True, verbose_name='myON Books Opened'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='current_dra',
            field=models.CharField(blank=True, max_length=10, verbose_name='Current DRA'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='current_lexile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Lexile'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='goal_dra',
            field=models.CharField(blank=True, max_length=10, verbose_name='Goal DRA'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='goal_lexile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goal Lexile'),
        ),
        migrations.AlterField(
            model_name='readingstats',
            name='starting_lexile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Starting Lexile'),
        ),
    ]
