# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 01:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0031_auto_20161008_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2016, 10, 24), verbose_name='Date of Message')),
                ('message', models.TextField(default='')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(default='Spanish and Art', max_length=255)),
                ('tuesday', models.CharField(default='Spanish and Art', max_length=255)),
                ('wednesday', models.CharField(default='Spanish and Art', max_length=255)),
                ('thursday', models.CharField(default='Spanish and Art', max_length=255)),
                ('friday', models.CharField(default='Spanish and Art', max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Teacher')),
            ],
        ),
    ]
