# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0032_morningmessage_specialschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningmessage',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 10, 24, 1, 7, 16, 416801, tzinfo=utc), verbose_name='Date of Message'),
        ),
    ]
