# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0033_auto_20161024_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningmessage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Message'),
        ),
    ]
