# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0036_librarydayschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningMessageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(default='Good Morning, Scholars!', max_length=100)),
                ('specialsmonday', models.CharField(default='Spanish and Art', max_length=255)),
                ('specialstuesday', models.CharField(default='Spanish and Art', max_length=255)),
                ('specialswednesday', models.CharField(default='Spanish and Art', max_length=255)),
                ('specialsthursday', models.CharField(default='Spanish and Art', max_length=255)),
                ('specialsfriday', models.CharField(default='Spanish and Art', max_length=255)),
                ('box1heading', models.CharField(default='Library Students', max_length=255)),
                ('box1monday', models.CharField(max_length=255)),
                ('box1tuesday', models.CharField(max_length=255)),
                ('box1wednesday', models.CharField(max_length=255)),
                ('box1thursday', models.CharField(max_length=255)),
                ('box1friday', models.CharField(max_length=255)),
                ('endingcomment', models.CharField(default="Let's have a fantastic day!", max_length=255)),
                ('signoffword', models.CharField(default='Love,', max_length=100)),
                ('signoffteacher', models.CharField(default='Mr. Trost and Ms. West', max_length=255)),
                ('moodmeter', models.BooleanField(default=True)),
                ('weather', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='librarydayschedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='specialschedule',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='LibraryDaySchedule',
        ),
        migrations.DeleteModel(
            name='SpecialSchedule',
        ),
    ]
