# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0037_auto_20161030_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morningmessage',
            options={'verbose_name': 'Morning Message', 'verbose_name_plural': 'Morning Messages'},
        ),
        migrations.AlterModelOptions(
            name='morningmessagesettings',
            options={'verbose_name': 'Morning Message Settings', 'verbose_name_plural': 'Morning Message Settings'},
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1friday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1monday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1thursday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1tuesday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1wednesday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255),
        ),
    ]
