# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0038_auto_20161030_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1friday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255, verbose_name='Box Content: Fri'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1heading',
            field=models.CharField(default='Library Students', help_text='Heading for the box at the top right. It can be used for anything and can have different information depending on the day of the week. I use mine to remind students to change out library books.', max_length=255, verbose_name='Side Box Heading'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1monday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255, verbose_name='Box Content: Mon'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1thursday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255, verbose_name='Box Content: Thu'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1tuesday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255, verbose_name='Box Content: Tue'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='box1wednesday',
            field=models.CharField(default='Noel, Travis, Aniya, Zaire', max_length=255, verbose_name='Box Content: Wed'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='endingcomment',
            field=models.CharField(default="Let's have a fantastic day!", max_length=255, verbose_name='Last Thought'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='greeting',
            field=models.CharField(default='Good Morning, Scholars!', max_length=100, verbose_name='Greeting'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='moodmeter',
            field=models.BooleanField(default=True, help_text='If you want a Mood Meter reminder to appear on your Morning Message Screen', verbose_name='Mood Meter'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='signoffteacher',
            field=models.CharField(default='Mr. Trost and Ms. West', max_length=255, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='signoffword',
            field=models.CharField(default='Love,', help_text='Love, Sincerely, etc.', max_length=100, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='specialsfriday',
            field=models.CharField(default='Spanish and Art', max_length=255, verbose_name='Friday Specials'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='specialsmonday',
            field=models.CharField(default='Spanish and Art', max_length=255, verbose_name='Monday Specials'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='specialsthursday',
            field=models.CharField(default='Spanish and Art', max_length=255, verbose_name='Thursday Specials'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='specialstuesday',
            field=models.CharField(default='Spanish and Art', max_length=255, verbose_name='Tuesday Specials'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='specialswednesday',
            field=models.CharField(default='Spanish and Art', max_length=255, verbose_name='Wednesday Specials'),
        ),
        migrations.AlterField(
            model_name='morningmessagesettings',
            name='weather',
            field=models.BooleanField(default=True, help_text='If you want a local weather box to appear on your Morning Message Screen', verbose_name='Weather'),
        ),
    ]
