# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0039_auto_20161103_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstats',
            name='starting_dra',
            field=models.CharField(blank=True, max_length=10, verbose_name='Starting DRA'),
        ),
    ]
