# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0040_readingstats_starting_dra'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='videos',
            field=models.BooleanField(default=False),
        ),
    ]
