# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0041_accountinfo_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='videos',
            field=models.BooleanField(default=False, help_text="Do 2nd Grade Videos appear on the student's portal page to view?", verbose_name='Video Access'),
        ),
    ]
