# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0042_auto_20161113_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='enrichmentreadworkscode',
            field=models.CharField(blank=True, help_text='Only for students in Enrichment', max_length=50, verbose_name='Enrichment Readworks Class Code'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='readworkscode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Readworks Class Code'),
        ),
    ]
