# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0045_auto_20161120_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='title',
        ),
    ]
