# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0046_auto_20161120_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='subject7',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='subject7', to='brain.Subject', verbose_name='Seventh Class'),
            preserve_default=False,
        ),
    ]
