# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0047_schedule_subject7'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-dateandtime'],
            },
        ),
    ]
