# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 11:39
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0018_auto_20160802_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXLSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\w\\-\\w\\.\\d+$', 'Pattern must match IXL format: D-A.12')], verbose_name='Skill ID')),
                ('skill_description', models.CharField(blank=True, max_length=200, verbose_name='Skill Description')),
                ('ixl_url', models.CharField(blank=True, max_length=300, verbose_name='IXL URL')),
            ],
            options={
                'verbose_name': 'IXL Skill',
                'verbose_name_plural': 'IXL Skills ',
            },
        ),
        migrations.CreateModel(
            name='IXLSkillScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=datetime.datetime.now, verbose_name='Date Recorded')),
                ('score', models.IntegerField()),
                ('ixl_skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.IXLSkill', verbose_name='IXL Skill ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'IXL Skill Score',
                'verbose_name_plural': 'IXL Skill Scores',
            },
        ),
    ]
