# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixlskill',
            options={'verbose_name': 'IXL Skill', 'verbose_name_plural': 'IXL Skills'},
        ),
        migrations.AlterModelOptions(
            name='ixlskillscores',
            options={'verbose_name': 'IXL Score', 'verbose_name_plural': 'IXL Scores'},
        ),
    ]
