# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0002_auto_20160802_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixlskill',
            options={'ordering': ['skill_id'], 'verbose_name': 'IXL Skill', 'verbose_name_plural': 'IXL Skills'},
        ),
        migrations.AddField(
            model_name='ixlskill',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ixlskill',
            name='ixl_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='IXL URL'),
        ),
        migrations.AlterField(
            model_name='ixlskill',
            name='skill_id',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\w+\\-\\w+\\.\\d+$', 'Pattern must match IXL format: D-A.12')], verbose_name='Skill ID'),
        ),
    ]
