# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0003_auto_20160804_2117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ixlskillscores',
            unique_together=set([('student_id', 'ixl_skill_id')]),
        ),
    ]
