# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 00:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0023_accountinfo'),
        ('ixl', '0005_auto_20160817_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date Created')),
                ('complete', models.BooleanField(default=False)),
                ('exercise1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_1', to='ixl.IXLSkill')),
                ('exercise10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_10', to='ixl.IXLSkill')),
                ('exercise2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_2', to='ixl.IXLSkill')),
                ('exercise3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_3', to='ixl.IXLSkill')),
                ('exercise4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_4', to='ixl.IXLSkill')),
                ('exercise5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_5', to='ixl.IXLSkill')),
                ('exercise6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_6', to='ixl.IXLSkill')),
                ('exercise7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_7', to='ixl.IXLSkill')),
                ('exercise8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_8', to='ixl.IXLSkill')),
                ('exercise9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_9', to='ixl.IXLSkill')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
