# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0024_auto_20161002_0935'),
        ('ixl', '0006_recommendationsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='IXLStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_practiced', models.IntegerField(blank=True, verbose_name='Last Practiced')),
                ('questions_answered', models.IntegerField(blank=True, verbose_name='Questions Answered')),
                ('time_spent', models.IntegerField(blank=True, verbose_name='Time Spent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
