# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0007_ixlstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ixlstats',
            name='last_practiced',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Practiced'),
        ),
        migrations.AlterField(
            model_name='ixlstats',
            name='questions_answered',
            field=models.CharField(blank=True, max_length=100, verbose_name='Questions Answered'),
        ),
        migrations.AlterField(
            model_name='ixlstats',
            name='time_spent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Time Spent'),
        ),
    ]
