# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0008_auto_20161002_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixlstats',
            options={'verbose_name': 'IXL Stat', 'verbose_name_plural': 'IXL Stats'},
        ),
    ]
