# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0009_auto_20161002_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ixlstats',
            name='last_practiced',
            field=models.IntegerField(blank=True, verbose_name='Last Practiced'),
        ),
        migrations.AlterField(
            model_name='ixlstats',
            name='questions_answered',
            field=models.IntegerField(blank=True, verbose_name='Questions Answered'),
        ),
        migrations.AlterField(
            model_name='ixlstats',
            name='time_spent',
            field=models.IntegerField(blank=True, verbose_name='Time Spent'),
        ),
    ]
