# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0010_auto_20161003_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixlskillscores',
            options={'ordering': ['student_id', 'ixl_skill_id'], 'verbose_name': 'IXL Score', 'verbose_name_plural': 'IXL Scores'},
        ),
    ]
