# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0011_auto_20161009_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendationSheet',
            new_name='Challenge',
        ),
    ]
