# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0012_auto_20161009_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='exercise11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_11', to='ixl.IXLSkill'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='exercise12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_12', to='ixl.IXLSkill'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='exercise13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_13', to='ixl.IXLSkill'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='exercise14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_14', to='ixl.IXLSkill'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='exercise15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_15', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_1', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_10', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_2', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_3', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_4', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_5', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_6', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_7', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_8', to='ixl.IXLSkill'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='exercise9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_9', to='ixl.IXLSkill'),
        ),
    ]
