# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0031_auto_20161008_2030'),
        ('ixl', '0013_auto_20161009_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=datetime.date.today, verbose_name='Date Assigned')),
                ('current_challenge', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='student_id',
        ),
        migrations.AddField(
            model_name='challengeassignment',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ixl.Challenge'),
        ),
        migrations.AddField(
            model_name='challengeassignment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster'),
        ),
    ]
