# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0014_auto_20161009_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='Challenge', max_length=250, verbose_name='Challenge Title'),
        ),
    ]
