# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0015_challenge_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['date', 'title'], 'verbose_name': 'IXL Challenge', 'verbose_name_plural': 'IXL Challenges'},
        ),
        migrations.AlterModelOptions(
            name='challengeassignment',
            options={'ordering': ['date_assigned', 'challenge', 'student_id'], 'verbose_name': 'IXL Challenge Assignment', 'verbose_name_plural': 'IXL Challenge Assignmentss'},
        ),
    ]
