# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0018_auto_20161105_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeassignment',
            name='current_challenge',
        ),
    ]
