# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0020_auto_20170106_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeexercise',
            name='required_score',
            field=models.IntegerField(default=80),
        ),
    ]
