# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ixl', '0022_auto_20170320_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeexercise',
            unique_together=set([('challenge', 'exercise_id')]),
        ),
    ]
