# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0046_auto_20161120_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('question', models.CharField(max_length=256)),
                ('pointvalue', models.PositiveIntegerField()),
                ('ordering', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='CriteriaScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('completed', models.BooleanField(default=False)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreit.Criteria')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('approved', models.CharField(default='NO', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
