# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'verbose_name': 'Criteria', 'verbose_name_plural': 'Criteria'},
        ),
        migrations.AlterModelOptions(
            name='criteriascore',
            options={'verbose_name': 'Criteria Score', 'verbose_name_plural': 'Criteria Scores'},
        ),
        migrations.AlterModelOptions(
            name='teacherapproval',
            options={'verbose_name': 'Teacher Approval', 'verbose_name_plural': 'Teacher Approvals'},
        ),
    ]
