# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0047_schedule_subject7'),
        ('scoreit', '0003_auto_20161124_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2016, 11, 26), verbose_name='Date')),
                ('hand', models.BooleanField(default=False)),
                ('slant', models.BooleanField(default=False)),
                ('transition', models.BooleanField(default=False)),
                ('please', models.BooleanField(default=False)),
                ('instruction', models.BooleanField(default=False)),
                ('material', models.BooleanField(default=False)),
                ('peer', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='criteriascore',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='criteriascore',
            name='student',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.DeleteModel(
            name='CriteriaScore',
        ),
    ]
