# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreit', '0007_auto_20161127_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='hand',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Raised Hand'),
        ),
        migrations.AlterField(
            model_name='score',
            name='instruction',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Instructions 1st Time'),
        ),
        migrations.AlterField(
            model_name='score',
            name='material',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Respected Materials'),
        ),
        migrations.AlterField(
            model_name='score',
            name='peer',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Respected Peers'),
        ),
        migrations.AlterField(
            model_name='score',
            name='please',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Please/Thank You'),
        ),
        migrations.AlterField(
            model_name='score',
            name='slant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='SLANT'),
        ),
        migrations.AlterField(
            model_name='score',
            name='transition',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Transitions'),
        ),
    ]
