# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0021_auto_20160927_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='NWEAScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[(14, '14-15'), (15, '15-16'), (16, '16-17'), (17, '17-18'), (18, '18-19'), (19, '19-20'), (20, '20-21'), (21, '21-22')], default=16, max_length=50)),
                ('season', models.CharField(choices=[(1, 'Fall'), (2, 'Winter'), (3, 'Spring')], default=1, max_length=50)),
                ('subdomain1', models.IntegerField(verbose_name='SubDomain 1')),
                ('subdomain2', models.IntegerField(verbose_name='SubDomain 2')),
                ('subdomain3', models.IntegerField(verbose_name='SubDomain 3')),
                ('subdomain4', models.IntegerField(verbose_name='SubDomain 4')),
                ('subdomain5', models.IntegerField(verbose_name='SubDomain 5')),
                ('subdomain6', models.IntegerField(verbose_name='SubDomain 6')),
                ('subdomain7', models.IntegerField(verbose_name='SubDomain 7')),
                ('subdomain8', models.IntegerField(default=141, verbose_name='SubDomain 8')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'NWEA Score',
                'verbose_name_plural': 'NWEA Scores',
            },
        ),
        migrations.CreateModel(
            name='NWEASkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('ixl_match', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'NWEA Skill',
                'verbose_name_plural': 'NWEA Skills',
                'ordering': ['rit_band', 'skill'],
            },
        ),
        migrations.CreateModel(
            name='RITBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[(1, 'Operations and Algebraic Thinking'), (2, 'Number and Operations'), (3, 'Measurement and Data'), (4, 'Geometry')], max_length=255)),
                ('subdomain', models.CharField(choices=[(1, 'Represent and Solve Problems'), (2, 'Analyze Patterns and Relationships'), (3, 'Understand Place Value, Counting, and Cardinality'), (4, 'Number and Operations in Base Ten'), (5, 'Number and Operations - Fractions'), (6, 'Geometric Measurement and Problem Solving'), (7, 'Represent and Interpret Data'), (8, 'Reason with Shapes Attributes, & Coordinate Plane')], max_length=255)),
                ('rit_band', models.PositiveIntegerField(choices=[(111, '111'), (121, '121'), (131, '131'), (141, '141'), (151, '151'), (161, '161'), (171, '171'), (181, '181'), (191, '191'), (201, '201'), (211, '211'), (221, '221'), (231, '231'), (241, '241')], default=151)),
            ],
            options={
                'verbose_name': 'RIT Band',
                'verbose_name_plural': 'RIT Bands',
                'ordering': ['domain', 'subdomain', 'rit_band'],
            },
        ),
        migrations.AddField(
            model_name='nweaskill',
            name='rit_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwea.RITBand'),
        ),
        migrations.AlterUniqueTogether(
            name='nweascore',
            unique_together=set([('student', 'year', 'season')]),
        ),
    ]
