# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwea', '0002_auto_20160927_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nweascore',
            name='subdomain8',
            field=models.IntegerField(verbose_name='SubDomain 8'),
        ),
    ]
