# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwea', '0004_auto_20160928_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nweascore',
            name='subdomain8',
            field=models.IntegerField(verbose_name='SubDomain 8'),
        ),
    ]
