# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwea', '0007_nweagoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nweaaverage',
            name='math',
        ),
        migrations.RemoveField(
            model_name='nweaaverage',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='nweaaverage',
            name='season',
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='lexile_fall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='lexile_spring',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='lexile_winter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='math_fall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='math_spring',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='math_winter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='reading_fall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='reading_spring',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nweaaverage',
            name='reading_winter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
