# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwea', '0008_auto_20170129_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nweascore',
            options={'verbose_name': 'NWEA Math Breakdown', 'verbose_name_plural': 'NWEA Math Breakdowns'},
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='lexile_fall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='lexile_spring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='lexile_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='math_fall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='math_spring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='math_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='reading_fall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='reading_spring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweaaverage',
            name='reading_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweagoal',
            name='math_spring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweagoal',
            name='math_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweagoal',
            name='reading_spring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nweagoal',
            name='reading_winter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
