# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0020_auto_20160805_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField(unique=True)),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_equivalent', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField(default=20)),
                ('minimum_passing_grade', models.IntegerField(default=18)),
            ],
            options={
                'verbose_name_plural': 'AMC Tests',
                'verbose_name': 'AMC Test',
            },
        ),
        migrations.CreateModel(
            name='AMCTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_taken', models.DateField(default=datetime.datetime.now, verbose_name='Date Taken')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.AMCTest')),
            ],
            options={
                'verbose_name_plural': 'AMC Test Scores',
                'verbose_name': 'AMC Test Score',
                'ordering': ['-date_taken', 'student'],
            },
        ),
    ]
