# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0018_auto_20160802_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
                ('date_taken', models.DateField(default=datetime.datetime.now, verbose_name='Date Recorded')),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
