# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amctestresult',
            options={'ordering': ['-date_tested', 'student'], 'verbose_name': 'AMC Test Score', 'verbose_name_plural': 'AMC Test Scores'},
        ),
     #   migrations.RemoveField(
     #       model_name='amctestresult',
     #       name='date_taken',
     #   ),
        migrations.AddField(
            model_name='amctestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date Tested'),
        ),
    ]
