# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0018_auto_20160802_1134'),
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AMC Test Score',
                'verbose_name_plural': 'AMC Test Scores',
            },
        ),
        migrations.CreateModel(
            name='AMCTestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(default=datetime.datetime.now, verbose_name='Date Recorded')),
            ],
        ),
        migrations.RemoveField(
            model_name='amc',
            name='student',
        ),
        migrations.DeleteModel(
            name='AMC',
        ),
        migrations.AddField(
            model_name='amctest',
            name='date_taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.AMCTestInstance'),
        ),
        migrations.AddField(
            model_name='amctest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster'),
        ),
    ]
