# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_auto_20160810_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amctestresult',
            name='date_taken',
        ),
    ]
