# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0018_auto_20160802_1134'),
        ('amc', '0002_auto_20160802_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCTestDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(default=datetime.datetime.now, verbose_name='Date Taken')),
            ],
        ),
        migrations.CreateModel(
            name='AMCTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.AMCTestDay')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
            options={
                'verbose_name': 'AMC Test Score',
                'verbose_name_plural': 'AMC Test Scores',
            },
        ),
        migrations.AlterModelOptions(
            name='amctest',
            options={},
        ),
        migrations.RemoveField(
            model_name='amctest',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='amctest',
            name='score',
        ),
        migrations.RemoveField(
            model_name='amctest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='amctest',
            name='test',
        ),
        migrations.AddField(
            model_name='amctest',
            name='grade_equivalent',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amctest',
            name='minimum_passing_grade',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amctest',
            name='name',
            field=models.CharField(default=5, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amctest',
            name='test_number',
            field=models.IntegerField(default=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amctest',
            name='topic',
            field=models.CharField(default=5, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amctest',
            name='total_questions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AMCTestInstance',
        ),
        migrations.AddField(
            model_name='amctestresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amc.AMCTest'),
        ),
    ]
