# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_remove_amctestresult_date_taken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amctestresult',
            unique_together=set([('student', 'test', 'date_tested')]),
        ),
    ]
