# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_auto_20160802_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amctest',
            name='minimum_passing_grade',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='amctest',
            name='total_questions',
            field=models.IntegerField(default=20),
        ),
    ]
