# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0019_auto_20160804_2117'),
        ('amc', '0004_auto_20160802_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amctest',
            options={'verbose_name': 'AMC Test', 'verbose_name_plural': 'AMC Tests'},
        ),
        migrations.AlterModelOptions(
            name='amctestday',
            options={'verbose_name': 'AMC Test Day', 'verbose_name_plural': 'AMC Test Days'},
        ),
        migrations.AddField(
            model_name='amctestday',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brain.CurrentClass'),
        ),
    ]
