# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_auto_20160810_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amctestresult',
            name='date_tested',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Tested'),
        ),
    ]
