# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_auto_20160804_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amctestresult',
            options={'ordering': ['-date_taken', 'student'], 'verbose_name': 'AMC Test Score', 'verbose_name_plural': 'AMC Test Scores'},
        ),
    ]
