# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 15:38
from __future__ import unicode_literals

import brain.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0036_librarydayschedule'),
        ('amc', '0005_auto_20160812_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCStartingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_test', models.IntegerField(verbose_name=brain.models.StudentRoster)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
