# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0006_amcstartingtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcstartingtest',
            name='starting_test',
            field=models.IntegerField(verbose_name='Starting Test'),
        ),
    ]
