# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0007_auto_20161030_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amcstartingtest',
            options={'verbose_name': 'AMC Starting Test', 'verbose_name_plural': 'AMC Starting Tests'},
        ),
    ]
