# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brain', '0020_auto_20160805_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAMCTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amc_test', models.IntegerField(default='1')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster')),
            ],
        ),
    ]
