# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20161224_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.FilePathField(path='static/images'),
        ),
    ]
