# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0047_schedule_subject7'),
        ('badges', '0004_auto_20161224_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickerassignment',
            options={'verbose_name': 'Earned Sticker', 'verbose_name_plural': 'Earned Stickers Assignments'},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster', unique=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stickerassignment',
            unique_together=set([('student', 'sticker')]),
        ),
    ]
