# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_auto_20161226_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stickerassignment',
            unique_together=set([]),
        ),
    ]
