# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0047_schedule_subject7'),
        ('badges', '0006_auto_20161226_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.StudentRoster'),
        ),
        migrations.AlterUniqueTogether(
            name='stickerassignment',
            unique_together=set([('student', 'sticker')]),
        ),
    ]
