# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_auto_20161226_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AddField(
            model_name='sticker',
            name='category',
            field=models.CharField(default='CGI', max_length=255),
        ),
        migrations.AddField(
            model_name='sticker',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
