# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0008_auto_20161227_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
